### ISSUE TITLE
implicit declaration of function 'tee_invoke_supp_plugin'

### ISSUE THREAD

**Issue by bucktaiwan** [linaro-swg/optee_examples#83]
Try lastest revision 0607ed40746afe4cb8993149a6f275df648f7bad

commit 0607ed40746afe4cb8993149a6f275df648f7bad (HEAD -> master, origin/master, origin/HEAD)
Author: Aleksandr Anisimov <a.anisimov@omprussia.ru>
Date:   Tue Dec 8 23:13:14 2020 +0300

Has compilation error
```
| plugin_ta.c: In function 'syslog_plugin_ping':
| plugin_ta.c:58:8: error: implicit declaration of function 'tee_invoke_supp_plugin' [-Werror=implicit-function-declaration]
|    58 |  res = tee_invoke_supp_plugin(&syslog_uuid, TO_SYSLOG_CMD, LOG_INFO,
|       |        ^~~~~~~~~~~~~~~~~~~~~~
| plugin_ta.c:58:8: warning: nested extern declaration of 'tee_invoke_supp_plugin' [-Wnested-externs]
```

**Comment by jforissier** [comment]
Hi @bucktaiwan,

It seems you need a more recent `optee_os`. The missing function was introduced by commit https://github.com/OP-TEE/optee_os/commit/e4ad5ccd3994b1abe0fd638c786b8d719732e2a5.

**Comment by bucktaiwan** [comment]
Great, thank you for pointing out.
